name: 'Generate Task definition'
description: "Update the environment variables section in the task_definition template"
inputs:
  task_definition_template_path:
    description: 'The path to the task_definition_template.json file'
    required: true
  secret_keys:
    description: 'The secret keys coming from vault'
    required: true
outputs:
  task_definition:
    description: 'The formatted data to go in task_definiton file'
runs:
  using: 'node12'
  main: 'dist/index.js'
